
#try  except
values = [10,5,6,0,9,8,8,2]

for value in values:
 try:
  print(10 / value)
  values[56]=40;
  print("try still continues")
 except ValueError:
  print("Please execute me before my dad Exception, otherwise I will be lost inside the Exeptio :(")      
 except Exception:
  print("General error occured")  
 else:
  print("I am only executed if there is no problem  :)")
 finally:
  print("I am always executed!/ even there is an unhandled exception!")

   

print("end of the code")    

print('hello')


#zero division error

#value error

#a change 

#change2

#change3
#change4

#change5